apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp-stag-deployment
  labels:
    app: lp-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp-stag
      track: stable
  template:
    metadata:
      labels:
        app: lp-stag
        track: stable
    spec:
      containers:
      - name: lp-stag
        image: renardarv/landing-page:buildnumber 
        ports:
        - containerPort: 8000
      restartPolicy: Always
