apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel-stag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-stag
      track: stable
  template:
    metadata:
      labels:
        app: laravel-stag
        track: stable
    spec:
      containers:
      - name: laravel-stag
        image: renardarv/laravel:buildnumber 
        ports:
        - containerPort: 8000
      restartPolicy: Always
